### ISSUE TITLE
No load_profile in example run_automated_wannier.py

### ISSUE THREAD

**Issue by ahzeeshan** [aiidateam/aiida-wannier90-workflows#13]
The example `run_automated_wannier.py` does not have a load_profile and gives the error with current aiida version.
`aiida.common.exceptions.ConfigurationError: Could not determine the current profile. Consider loading a profile using `aiida.load_profile()`.`

**Comment by qiaojunfeng** [comment]
Hi Zeeshan, the shebang of the `run_automated_wannier.py` is
https://github.com/aiidateam/aiida-wannier90-workflows/blob/ef4959799cca1dd1b7fe09cb408ab747134c175d/examples/workflows/run_automated_wannier.py#L1
`runaiida` will automatically load the current profile. 
When you replace the shebang with something like `/usr/bin/env python`, you need to manually `aiida.load_profile()`.
Could you check the shebang in your script? Thanks.

**Comment by ahzeeshan** [comment]
Hi @qiaojunfeng 
Thanks. I was running `python run_automated_wannier.py` instead of `./run_automated_wannier.py` which was causing the problem.
