### ISSUE TITLE
support python 3.5?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-wannier90-workflows#2]
I notice that this is currently the only plugin in the Quantum Mobile that requires python >= 3.6 [1] and therefore [fails to install on ubuntu 16.04](https://travis-ci.org/github/marvel-nccr/ansible-role-aiida/jobs/664151460?utm_medium=notification&utm_source=github_status).

Is this necessary?

[1] Note: While the setup.json of aiida-wannier90 might look similar, somehow the requirement ending up on pypi is different: 

[aiida-wannier90](https://pypi.org/project/aiida-wannier90/#files): Requires: Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*
[aiida-wannier90-workflows](https://pypi.org/project/aiida-wannier90-workflows/#files): Requires: Python >=3.6

**Comment by giovannipizzi** [comment]
I think it's ok and we can do this now (maybe you are looking at the develop branch of `aiida-wannier90`, where we dropped py2, that's why they look similar now).

However note that in `aiida-wannier90` we dropped py2 and are supporting only py >=3.6, so this problem will be there soon anyway. How much is this a problem?

**Comment by ltalirz** [comment]
Not a major problem - I can drop support for ubuntu 16.04.

Would just not have liked to do this without reason.

**Comment by qiaojunfeng** [comment]
Thanks! Now I keep the `python_requires` same as `aiida-wannier90` v2.0.1: `>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*` https://github.com/aiidateam/aiida-wannier90-workflows/commit/0e3a4e901827906716ebee291b10625788f00f33

**Comment by sphuber** [comment]
Just for reference, [python 3.5 will be EOL on September 13 2020](https://devguide.python.org/#branchstatus) anyway, so pretty soon `aiida-core` will also be dropping support for it.

**Comment by giovannipizzi** [comment]
Fixed in v1.0.1
